In [1]:
import os
import pandas as pd
from PIL import Image

In [34]:
players = {"name":"players"}
enemy1 = {'name':"enemy-1"}

In [35]:
players['player-1'] = range(1,26)
players['player-2'] = [26,27,35,36,28,37,29,38,30,31,32,33,34,39,40,41,42,47,43,48,44,49,50,45,46]
players['blast-small'] = [60,61]
players['blast-medium'] = [56,57]
players['blast-large'] = [51]

players['actions'] = ['player-1','player-2','blast-small','blast-medium','blast-large']
players['map'] = pd.read_csv(f'C:/Users/sjege/Documents/GitHub/Project1/assets/sprites/players/players-sprite-map.csv', header=None)
players['map'].rename(columns={0:'SPRITE_NUM',1:'TOP_X',2:'TOP_Y',3:'WIDTH',4:'HEIGHT'})

    SPRITE_NUM  TOP_X  TOP_Y  WIDTH  HEIGHT
0      sprite1     22     14     29      44
1      sprite2     69     14     31      44
2      sprite3    116     14     32      44
3      sprite4    163     14     34      44
4      sprite5    211     14     35      44
..         ...    ...    ...    ...     ...
197  sprite198     81    258      5      13
198  sprite199    195    258      1       1
199  sprite200    125    260     11      11
200  sprite201    422    261      3       5
201  sprite202    261    262      3       4

[202 rows x 5 columns]

In [37]:
enemy1['enemy-1'] = [1,9,10,11,2,12,13,3,4,5,14,6,7,8,15,22,23,24,16,17,18,25,26,19,20,21,27,28,29,35,36,37,30,38,39,40,31,41,42,32,33,34,51,43,44,45,46,52,53,54,47,48,49,55,56,50,57,58,60,61,59,62,63,64]

enemy1['actions'] = ['enemy-1']
enemy1['map'] = pd.read_csv(f'C:/Users/sjege/Documents/GitHub/Project1/assets/sprites/enemy-1/enemy-1-sprite-map.csv', header=None)
enemy1['map'].rename(columns={0:'SPRITE_NUM',1:'TOP_X',2:'TOP_Y',3:'WIDTH',4:'HEIGHT'})

    SPRITE_NUM  TOP_X  TOP_Y  WIDTH  HEIGHT
0      sprite1     13     16     42      42
1      sprite2    206     16     39      42
2      sprite3    352     16     33      42
3      sprite4    401     16     31      42
4      sprite5    451     16     27      42
..         ...    ...    ...    ...     ...
118  sprite119    453    248      8       9
119  sprite120    462    248      7       9
120  sprite121    507    248      7       8
121  sprite122    517    248      8       9
122  sprite123    526    248      8       9

[123 rows x 5 columns]

In [ ]:
frieza['transform'] = [1,2]
frieza['idle'] = [29]
frieza['walk'] = [23,25,26,22,88,92]
frieza['tail_whip'] = [89,90,91]
frieza['key_blast'] = [72,70,67,65,63]
frieza['explosion'] = [68,66,62,56]
frieza['disk_attack'] = [82,87,74,73,71,69]
frieza['damage'] = [121,135,131,133,132,130,137,134,136]
frieza['actions'] = ['transform','idle','walk','tail_whip','key_blast','explosion','disk_attack','damage']

In [38]:
characters = [players,enemy1]

### Function to create action images

In [39]:
def extract_sprites(character):
    name = character['name']
    actions = character['actions']
#     character['map'] = pd.read_csv(f'./sprites/{name}/{name}-map.csv')
    for action in actions:
        action_num = 1
        for sprite_idx in character[action]:
            _,left,upper,width,height = character['map'].iloc[sprite_idx-1]
            right=left+width
            lower=upper+height
            im = Image.open(f"C:/Users/sjege/Documents/GitHub/Project1/assets/sprites/sprite-sheets/{name}-transparent.png").crop((left, upper, right, lower))
            im.save(f"C:/Users/sjege/Documents/GitHub/Project1/assets/sprites/{name}/{name}-{action}-{action_num}.png")
            action_num+=1

In [40]:
for character in characters:
    extract_sprites(character)

## Practice and Scratchwork

In [ ]:
_,left,upper,width,height = goku_map_df.iloc[0]
right=left+width
lower=upper+height
im = Image.open("./sprites/goku/goku-spritesheet-transparent.png").crop((left, upper, right, lower))
display(im)
im1
display(im)

In [ ]:
im.save("./sprites/goku/goku-idle-1.png")